### ISSUE TITLE
Visualize transfer during traning?

### ISSUE THREAD

**Issue by CJHFUTURE** [eridgd/AdaIN-TF#5]
Hi, just wondering if it's possible to view the visual transfers as it progresses through training?
Not sure how this is done in tensorflow but in the original torch implementation you can view the training images . Any ideas?
Cheers

**Comment by eridgd** [comment]
Sample images are written to tensorboard during training, to see this:

`tensorboard --logdir /path/to/checkpointdir`

Then open http://localhost:6006
